apps:
  - name: config-manager
    components:
      - name: config-manager
        host: local
        repo: ./deploy
        path: clowdapp.yml
        parameters:
          CM_LOG_LEVEL: debug
          CM_LOG_FORMAT: json
  - name: playbook-dispatcher
    components:
      - name: playbook-dispatcher
        host: github
        repo: RedHatInsights/playbook-dispatcher
        path: deploy/clowdapp.yaml
        parameters:
          REPLICAS_API: 1
          REPLICAS_RESPONSE_CONSUMER: 1
          REPLICAS_VALIDATOR: 1
          DB_SSLMODE: disable
          RBAC_IMPL: mock
          RBAC_HOST: mock
          CLOUD_CONNECTOR_IMPL: impl
          CLOUD_CONNECTOR_HOST: cloud-connector
          PSK_AUTH_TEST: xwKhCUzgJ8
          TENANT_TRANSLATOR_HOST: mock
          TENANT_TRANSLATOR_IMPL: mock
  - name: host-inventory
    components:
      - name: host-inventory
        host: github
        repo: RedHatInsights/insights-host-inventory
        path: deployment.yaml
        parameters:
          BYPASS_RBAC: "true"
          XJOIN_SEARCH_HOST: xjoin-search
