// Package controllers provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package controllers

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/pkg/errors"
)

// Account defines model for Account.
type Account string

// AccountState defines model for AccountState.
type AccountState struct {
	Account *Account `json:"account,omitempty"`
	Id      *StateID `json:"id,omitempty"`
	Label   *Label   `json:"label,omitempty"`
	State   *State   `json:"state,omitempty"`
}

// AccountStateInput defines model for AccountStateInput.
type AccountStateInput struct {
	Account *Account `json:"account,omitempty"`
	State   *State   `json:"state,omitempty"`
}

// Hostname defines model for Hostname.
type Hostname string

// Initiator defines model for Initiator.
type Initiator string

// Label defines model for Label.
type Label string

// Run defines model for Run.
type Run struct {
	Account   *Account   `json:"account,omitempty"`
	CreatedAt *Timestamp `json:"created_at,omitempty"`
	Hostname  *Hostname  `json:"hostname,omitempty"`
	Id        *RunID     `json:"id,omitempty"`
	Initiator *Initiator `json:"initiator,omitempty"`
	Label     *Label     `json:"label,omitempty"`
	Status    *RunStatus `json:"status,omitempty"`
	UpdatedAt *Timestamp `json:"updated_at,omitempty"`
}

// RunCreated defines model for RunCreated.
type RunCreated struct {

	// status code of request
	Code     *int      `json:"code,omitempty"`
	Hostname *Hostname `json:"hostname,omitempty"`
}

// RunID defines model for RunID.
type RunID string

// RunStatus defines model for RunStatus.
type RunStatus string

// List of RunStatus
const (
	RunStatus_failure RunStatus = "failure"
	RunStatus_running RunStatus = "running"
	RunStatus_success RunStatus = "success"
)

// Runs defines model for Runs.
type Runs []Run

// RunsCreated defines model for RunsCreated.
type RunsCreated []RunCreated

// State defines model for State.
type State struct {
	AdditionalProperties map[string]string `json:"-"`
}

// StateArchive defines model for StateArchive.
type StateArchive struct {
	Account   *Account   `json:"account,omitempty"`
	CreatedAt *Timestamp `json:"created_at,omitempty"`
	Id        *StateID   `json:"id,omitempty"`
	Initiator *Initiator `json:"initiator,omitempty"`
	Label     *Label     `json:"label,omitempty"`
	State     *State     `json:"state,omitempty"`
}

// StateArchives defines model for StateArchives.
type StateArchives []StateArchive

// StateID defines model for StateID.
type StateID string

// Timestamp defines model for Timestamp.
type Timestamp time.Time

// Limit defines model for Limit.
type Limit int

// Offset defines model for Offset.
type Offset int

// RunIDParam defines model for RunIDParam.
type RunIDParam RunID

// RunsFilter defines model for RunsFilter.
type RunsFilter Label

// RunsSortBy defines model for RunsSortBy.
type RunsSortBy string

// List of RunsSortBy
const (
	RunsSortBy_created_at      RunsSortBy = "created_at"
	RunsSortBy_created_at_asc  RunsSortBy = "created_at:asc"
	RunsSortBy_created_at_desc RunsSortBy = "created_at:desc"
)

// StateIDParam defines model for StateIDParam.
type StateIDParam StateID

// GetChangesParams defines parameters for GetChanges.
type GetChangesParams struct {

	// Maximum number of results to return
	Limit *Limit `json:"limit,omitempty"`

	// Indicates the starting position of the query relative to the complete set of items that match the query
	Offset *Offset `json:"offset,omitempty"`
}

// GetRunsParams defines parameters for GetRuns.
type GetRunsParams struct {
	Filter *RunsFilter `json:"filter,omitempty"`
	SortBy *RunsSortBy `json:"sort_by,omitempty"`

	// Maximum number of results to return
	Limit *Limit `json:"limit,omitempty"`

	// Indicates the starting position of the query relative to the complete set of items that match the query
	Offset *Offset `json:"offset,omitempty"`
}

// PostRunsJSONBody defines parameters for PostRuns.
type PostRunsJSONBody AccountState

// PostStatesJSONBody defines parameters for PostStates.
type PostStatesJSONBody AccountStateInput

// PostRunsJSONRequestBody defines body for PostRuns for application/json ContentType.
type PostRunsJSONRequestBody PostRunsJSONBody

// PostStatesJSONRequestBody defines body for PostStates for application/json ContentType.
type PostStatesJSONRequestBody PostStatesJSONBody

// Getter for additional properties for State. Returns the specified
// element and whether it was found
func (a State) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for State
func (a *State) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for State to handle AdditionalProperties
func (a *State) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for State to handle AdditionalProperties
func (a State) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}
