// Package controllers provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package controllers

import (
	"time"
)

// Account defines model for Account.
type Account string

// AccountState defines model for AccountState.
type AccountState struct {
	Account *Account `json:"account,omitempty"`
	Id      *StateID `json:"id,omitempty"`
	Label   *Label   `json:"label,omitempty"`
	State   *State   `json:"state,omitempty"`
}

// Initiator defines model for Initiator.
type Initiator string

// Label defines model for Label.
type Label string

// State defines model for State.
type State struct {
	ComplianceOpenscap string `json:"compliance_openscap"`
	Insights           string `json:"insights"`
	Remediations       string `json:"remediations"`
}

// StateArchive defines model for StateArchive.
type StateArchive struct {
	Account   *Account   `json:"account,omitempty"`
	CreatedAt *Timestamp `json:"created_at,omitempty"`
	Id        *StateID   `json:"id,omitempty"`
	Initiator *Initiator `json:"initiator,omitempty"`
	Label     *Label     `json:"label,omitempty"`
	State     *State     `json:"state,omitempty"`
}

// StateArchives defines model for StateArchives.
type StateArchives struct {

	// A number of entries returned from offset
	Count *int `json:"count,omitempty"`

	// A max number of entries to return
	Limit *int `json:"limit,omitempty"`

	// A number representing he starting point for retrieving entries
	Offset *int `json:"offset,omitempty"`

	// Query results
	Results *[]StateArchive `json:"results,omitempty"`

	// A total count of found entries
	Total *int `json:"total,omitempty"`
}

// StateID defines model for StateID.
type StateID string

// Timestamp defines model for Timestamp.
type Timestamp time.Time

// Limit defines model for Limit.
type Limit int

// Offset defines model for Offset.
type Offset int

// StateIDParam defines model for StateIDParam.
type StateIDParam StateID

// GetStatesParams defines parameters for GetStates.
type GetStatesParams struct {

	// Maximum number of results to return
	Limit *Limit `json:"limit,omitempty"`

	// Indicates the starting position of the query relative to the complete set of items that match the query
	Offset *Offset `json:"offset,omitempty"`
}

// UpdateStatesJSONBody defines parameters for UpdateStates.
type UpdateStatesJSONBody State

// GetPlaybookPreviewJSONBody defines parameters for GetPlaybookPreview.
type GetPlaybookPreviewJSONBody State

// UpdateStatesJSONRequestBody defines body for UpdateStates for application/json ContentType.
type UpdateStatesJSONRequestBody UpdateStatesJSONBody

// GetPlaybookPreviewJSONRequestBody defines body for GetPlaybookPreview for application/json ContentType.
type GetPlaybookPreviewJSONRequestBody GetPlaybookPreviewJSONBody

