{
 "title": "Config-Manager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(\n          api_3scale_gateway_api_time_bucket{exported_service=\"config-manager\", le=\"2000.0\"}[24h])\n        ) / sum(rate(\n          api_3scale_gateway_api_time_bucket{exported_service=\"config-manager\", le=\"+Inf\"}[24h])\n        ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-5xx response",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"config-manager\", status!=\"5xx\"}[24h])) \n    /\n    sum(rate(api_3scale_gateway_api_status{exported_service=\"config-manager\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Playbook Generator Errors",
   "type": "stat",
   "description": "Errors returned while generating playbooks",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(config_manager_api_playbooks_requested_error_total[5m]))"
    }
   ]
  },
  {
   "title": "Playbooks Served",
   "type": "stat",
   "description": "number of playbooks provided",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(config_manager_api_playbooks_requested_ok_total[5m]))"
    }
   ]
  },
  {
   "title": "Request Payload Verification Errors",
   "type": "stat",
   "description": "Verification errors when updating account state",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(config_manager_api_request_payload_verification_error[5m]))"
    }
   ]
  },
  {
   "title": "Connector Errors",
   "type": "graph",
   "description": "Errors returned by connectors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(config_manager_api_cloud_connector_error_total[5m]))",
     "legendFormat": "Cloud Connector"
    },
    {
     "expr": "sum(increase(config_manager_api_inventory_error_total[5m]))",
     "legendFormat": "Inventory"
    },
    {
     "expr": "sum(increase(config_manager_api_playbook_dispatcher_error_total[5m]))",
     "legendFormat": "Playbook Dispatcher"
    }
   ]
  },
  {
   "title": "Config-Manager 5xx",
   "type": "graph",
   "description": "500 error returned by config-manager",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(config_manager_api_error_total{subtype=\"get_account_state\",type=\"db\"}[5m]))",
     "legendFormat": "Get Account State"
    },
    {
     "expr": "sum(increase(config_manager_api_error_total{subtype=\"get_state_changes\",type=\"db\"}[5m]))",
     "legendFormat": "Get State Changes"
    },
    {
     "expr": "sum(increase(config_manager_api_error_total{subtype=\"update_account_state\",type=\"db\"}[5m]))",
     "legendFormat": "Update Account State"
    }
   ]
  }
 ]
}