// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXTY/bNhD9KwRbwBfHcvNx0a0p2mDRr8WmPSWLYEyObKYUqR2O3BgL//eCIym217Lr",
	"IJsWKHqyyCHfDIdv+Mb32sS6iQEDJ13e62RWWIN8XlOsnMf82VBskNihGMCY2AZ+52we8aZBXerE5MJS",
	"b6caDLs17pkWMXqEkG3ZmXcQzCk7ITDad8Cj0GKONGpzIbnlqjvFMXCAGke3RVqeOkjTJeCUmbBG64Bd",
	"DKNOt9NhKi7eo2G93UqYVZTVjnNutYmhcssnNQRYIumpXiMlF4Mu9VOJr8EAjdOlfjabz+Z6qhvglTgs",
	"Gg+bRYx/yGiJkjOLyZBruIP4LobE1BpOCoJVhNxSSArUtyG5hUc1QKjUOoY8w1F1MbWECtQqJlZVJMUr",
	"VIR3LSZGq/rczLRESJKFK6tL/Qr5useUWAlqZKSkyzf32uWY7lqkjR6uZD/LOad3rSO0umRqcdrTcST9",
	"29u8ODUxpI6UT+fz/GNiYAySCWga74xEVnx4soHa7wi+h7h/OYfJ+/XHfAHPj4AZP3DOfT7N/ZkQjwBf",
	"glU3XQo75OePhfxLZPVDbIPNuC8eL+KrwEgBvHqNtEZS3xNFEmqntq6BNrrUN8jkcI0KwjGtTjJHQIp+",
	"cJrAO3DVwNKF/DooIIKNitWAlT66cRYDu8rlRd0rNVO/rVD9fvOTEt6pHSPVxLva8UQqYxKrKiFPlIGg",
	"FqjahDaXwuC0P0RqPacO0mIFrWe1Bt9iDmaAc0m9mJ9aM7hxSc3Hi2fIyEXFIy71uTqZjm/s4tCPV2Hv",
	"U3xArkPRkMvYc+MCY37wttP+EKOmPsxRW38b2egYa/n4mrDSpf6q2Kla0UtaMejZ7l0WHsk4MvgxL9v9",
	"J+lNv27aH2YXwu30339N/uGqf4WsQHmXOPMavP9YjCKdMY2pkai71FuUOfB+o6RfkHkV8M/TytLtHm6x",
	"uxhM/DLazWfw8nO6lfMtxwX9wT63+kAOvO65eIA3zrhD+dweFfA3n5Soi4rpmD3dPYkSPTtSuC/iMavf",
	"z9HKu/+fKrKhYPYL41A4i3tnt5eoZ2rQuMqZAWZfKhcbkbeJsxOVu8udSJ4V1qtKTIIMvhe5t9q0RBj4",
	"rc4iJzo6gIw4mIqhzk0mocHAu/hSblclfKtcSIxgzynmCcHM7nay90WbzEfj8/+N5ydI0ENid2hJtnU8",
	"aMnrUhfQuOLw31axzn+xHhbNa4ZlZlO3bcXcpLLIu2cmhhQ9zlJeMSO0K+CZifXF0NcUbWtkcA7/75Fv",
	"t38FAAD///SYyiK5DwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
