# This playbook will install the required OpenSCAP packages to get your systems ready to be used
# with Insights Compliance service.
#
# After running this playbook, perform the following steps manually:
# 1. Create a Compliance policy in cloud.redhat.com and associate the required systems.
# 2. Run `insights-client --compliance` on your system to report Compliance to cloud.redhat.com

- name: Compliance OpenSCAP Setup
  hosts: localhost
  become: yes
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldUbEhRWGRqZG5jMU9FUXJhalZ3VGtGUmFWb3hlRUZCYTJvM2NV
      WkdielZpVVVFd05uVmtXU3M0Y1ZsNlRVUTFObUpOY0dvNE0xRUtXRzlLY25NdmIyVkJSVmxVWmxk
      NVJVWTBZMWxhYzFVck9YTnVVazVwTTJ0bU5XNURhbWRDYTFaelNrcDNUVXA0VnpkbWFDdFljM1F4
      TkdremJESldUZ28yZDJ4TE1tUXJNeXRKU3l0WmVVaHNORmR3UVU1d01HTnpTMmt6WVZkclNYazJi
      MjlJY1RSV0x5czBNbTAzYlVsRFFTdGFNMXAxU1VkaFJXTXZXRFE1Q21RM1FTOTFOMFF6TUV4QlVt
      OUJSR3BEY2pKeE5qazRieXRITTNObVJEUnNiR3hKVlN0RE1ITlViMjlvV2xCS2NVUXpkbHBRVlVW
      TFVtRnplRFE1ZUZNS04xaExUbE5pWmxkU1VuRTFOVWhOV1drek9GVjJTRk56ZDNGb1VYaE5jRXRK
      VkRkMFYyNTFjME5IYTBsbE56ZHFOa3h1UkN0dFUzSXpWV1JHV0d0T2NncG5WVlpLWlVzeWVuRlRU
      eXRoYTB4d01XUXdVMHQwVEdaemQzUlhSbFJDU0doVGVtUkdkR2RYV1M5NmEyNWtWRWRPTWxJeGIy
      VndNUzlzVFZKcE5HY3dDak5oTmpVeFRGbG1kR0pZZHk5cE4xQmFaRUl3Ynpsb1RXWnlhRlJzUTFK
      UmJXZHpUa2xHZW1wc1VtTkxlVU5LUzNSNlJrOU5keTlNWlc5elNIRklTbllLZEZkelRtMUxNV0ky
      VXpseE1UbFFUMEZKYUhkQ2FHcFNkbXMyWkRaak5ITXlPRXhHWWsxU1ZGQjFUa3gzUmk5cE5FWlJk
      M053U2l0QlpHeFJWMUJrY3dwdWFFNVlVRTlUUWtkUmFEaDFia2xDV0cxeWNVUnRlRWQ0WmpsNWJG
      UTFaamwzWnpsVWJXVm1XRFZLTTAxV1EyOVZSMmhKUWpVclEyMUlWV0ZPVGpST0NreFJTR2hqV1hW
      M2JubFFabFZzYzNoR1dIZFpNRmxGVWtWdVdVOXhkRGRFTUVoV1VtNXhObVYxU25kcU9GVlRLMUoy
      VjJOMFl6VkVNa1ptVTJwSlkyb0tTM1JKTWtKWVF6a3JSRWh6U3pOMGQxRjBhV1pXY0ZSb2QyYzRh
      RVZuUzBRemFrVnRhWEkxWTBWb1ZtZFFTMGhWWldKQ1VESk5kbnBrWm5kSlUzUlpNUXAxV0RoRFpt
      UldabGxsWnowS1BVSnFhSFFLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  tasks:
    - name: Install OpenSCAP packages for Compliance service
      ansible.builtin.package:
        name:
          - openscap
          - openscap-scanner
          - scap-security-guide
        state: latest
      when:
        - ansible_facts.ansible_cmdline.ostree is undefined
