# Steps required to get your system ready to use the Insights Client:
# 1. Yum install the insights-client
# 2. Register the insights-client
# 3. Modify file permissions
- name: Insights Setup
  hosts: localhost
  become: yes
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldUSnNNREpqZG5jMU9FUXJhalZ3VGtGUloyNXJVUzh2WTJadVV6
      Z3JSSFV6VGxCNWVqaHZOemhOU20wNVRUbG9UREZsTTNWeVR6Z0tSRm8wYWtkVVdrSlZZVmhOV0ZO
      SlJHdEhUMVJYZDIxUWVubHRVVEJFV25Kc2EyRnhVREIwUTJSNlFrRTFhamRuT1V0eFpWbFpVMnBW
      U2twUGNXeGxNZ3BKYWpoamVpdG9lVFJPYVhGWldERklUREp0TlRCbFdGUkdhRVJwYTNkT1Z6TkpO
      V1ZrYTNGSGVHWk1SVzFhZDNGWVNVOWFkRGxYU0hOT2QySldZVEY1Q20xRWNHTlVUbmh0U3psSWNG
      bzBabmRhU0dsVlpEUlJlRVV4VERsMlMyNUZkRE15TWtsMWFWTlplWEJ4TURORllVVmhjbmRhWlVZ
      M2RGbzJhRXB1T0VJS1NuUTFXVFpvVWtSV1psTTNiQ3MwTDFjclUzWmFVVE5aU0hNMU1WVnViWGd4
      VW5Sb1YxVmpiVUowZFhNeVFpOVpXU3R1TlRreFRrdDVSVEJzZGpGTWRBcGtSaTh4ZWpCWVVsUTBj
      VmhVV0hCV2NrVm9WR1Z6Y210MFRWTnZNQ3N3ZDNoTk1EaDRNMWhhYkROMWJ6UlNVM0pzVTNOWlMz
      ZEVWalpQVjNVeE1uaFRDa0YxYkVWTFpWSXdkWE5RWVc1VVl5OXFlRlZUZUVkc1RFZHFlbko0Ym1a
      SGFEaEVSVXBFVGxwWVdXaFdRMUpxVFc1emVXczJkVWxTV1dWSGVWcDVRMHdLVWs0NWFFVlFSV0ZE
      ZEZKTE56WnJTMVp2ZW5CRmJVRmthbUVyVUV0Q0wySXpWa2xYTWtnMGRFUndRVXd4ZURneFJIVm9W
      bTFoTTJKSFdpOWlZMmhKYVFvM1ExaG5UbE5SZVc5UE9FTlNjWEJrZVd4eVZYZHZZbVZJYzJ0Vk1E
      azFaMlpZY2xwcloxQjBSVlZrUlVrd2NWbHlaWGN4WkVSVFJHSXpjMDlKYlRSMUNqVndTVXQ1ZUM5
      Sll5OXpjbkZLWjFGeFpsaFZOM0ZrVFZCYU5tdHBOMUZ0TTNoUlpHSkdhUzlyY0VwSWRtRTBTRU13
      ZUhkRmNIcHdkM05CZVRVMVkwd0tWamxzY0VoNWEyOUlabGxXZDNGR1REbHBUSGh1TDA1eWVXUXdi
      M0kwV2tndlRpczFkMVJTY1c0cmIyMVlUV2xVVFhsb09HWlplRnBHUTNKdFYxbG5NUXBKT1ZOcVJY
      VlhRVGhTYnowS1BYWTFOMHdLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  tasks:
    - name: Install latest insights-client, rhc, rhc-worker-playbook
      yum:
        name:
          - insights-client
          - rhc
          - rhc-worker-playbook
        state: latest

    # With legacy_upload=True: Insights API says this machine is NOT registered.
    # With legacy_upload=False: This host is unregistered.
    - name: Get insights-client's status
      command: insights-client --status
      changed_when: false
      failed_when: false
      register: result
    - name: Register insights-client
      command: insights-client --register
      when: '"NOT registered" in result.stdout or "unregistered" in result.stdout'

    # insights_remove.yml stops and disables insights-client.timer, but leaves host registered.
    - name: Schedule insights-client runs
      command: insights-client --enable-schedule
